[profile.default]
src = "src/lib/contracts/src"
out = "src/lib/contracts/out"
libs = ["src/lib/contracts/lib"]
remappings = [
    "forge-std/=src/lib/contracts/lib/forge-std/src/",
    "ds-test/=src/lib/contracts/lib/ds-test/src/"
] 
